### ISSUE TITLE
Não está permitindo assinar xml com SHA256

### ISSUE THREAD

**Issue by transis2** [OpenAC-Net/OpenAC.Net.DFe.Core#1]
Teste efetuado com Windows 10 e .net 4.5.2

Exemplo de código para simular o erro dentro do projeto OpenAC.Net.NFSe:

```
        protected override void AssinarEnviarSincrono(RetornoEnviar retornoWebservice)
        {
            retornoWebservice.XmlEnvio = XmlSigning.AssinarXmlTodos(retornoWebservice.XmlEnvio, "Rps", "InfDeclaracaoPrestacaoServico", Certificado, true, false, true, SignDigest.SHA256);
            retornoWebservice.XmlEnvio = XmlSigning.AssinarXml(retornoWebservice.XmlEnvio, "EnviarLoteRpsSincronoEnvio", "LoteRps", Certificado, true, false, true, SignDigest.SHA256);
        }
```

Exception:
```
OpenAC.Net.DFe.Core.OpenDFeException
  HResult=0x80131600
  Message=Erro ao efetuar assinatura digital.
  Source=OpenAC.Net.DFe.Core
  StackTrace:
   at OpenAC.Net.DFe.Core.XmlSigning.AssinarXmlTodos(String xml, String docElement, String infoElement, String signAtribute, X509Certificate2 certificado, Boolean comments, Boolean identado, Boolean showDeclaration, SignDigest digest)
   at OpenAC.Net.DFe.Core.XmlSigning.AssinarXmlTodos(String xml, String docElement, String infoElement, X509Certificate2 certificado, Boolean comments, Boolean identado, Boolean showDeclaration, SignDigest digest)
   at OpenAC.Net.NFSe.Providers.ProviderSIAPNet.AssinarEnviarSincrono(RetornoEnviar retornoWebservice) in /_/src/OpenAC.Net.NFSe/Providers/SIAPNet/ProviderSIAPNet.cs:line 55
   at OpenAC.Net.NFSe.Providers.ProviderBase.EnviarSincrono(Int32 lote, NotaServicoCollection notas) in /_/src/OpenAC.Net.NFSe/Providers/ProviderBase.cs:line 374
   at OpenAC.Net.NFSe.OpenNFSe.Enviar(Int32 lote, Boolean sincrono) in /_/src/OpenAC.Net.NFSe/OpenNFSe.cs:line 91

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
CryptographicException: Chave inválida para uso no estado especificado.

```

![image](https://user-images.githubusercontent.com/4941173/168159677-fffa8d6e-1880-4887-8ab6-a78af8b371f1.png)

**Comment by transis2** [comment]
Teve casos de provedores que eu nao adicionei o Transform XmlDsigC14N e deu certo

reference.AddTransform(new XmlDsigC14NTransform(comments));
